---
title: "Untitled"
author: "Office of Marketing and Brand Management"
date: "2/20/2020"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(knitr)
library(janitor)
library(tidyr)
library(zoo)
library(lubridate)
library(hms)
library(dplyr)
library(ggplot2)
library(gtable)
library(grid)
library(ggpubr)
library(kableExtra)
library(scales)
```


```{r}
FM <- read.csv("file:///Z:/DAA/Marketing/MKT_output.csv", header = T, stringsAsFactors = F)
```

```{r}
FM <- FM %>% filter(Master_Adname_Type == "NC")
FM <- FM %>% mutate(Code_Audience = ifelse(Master_Adname == "FA20_BR_FB_VID__TL_UG_D_1",  "TL", Code_Audience ), Code_Product = ifelse(Master_Adname == "FA20_BR_FB_VID__TL_UG_D_1",  "UG", Code_Product))
FM <- FM %>% select(1:8, 13, 15:19, 21:24, 26, 28:29, 31:39) %>% select(Master_Date, everything())
```

```{r}
FM <- FM %>% mutate_at(10:30, ~replace(., is.na(.), 0)) %>% mutate(Master_Date = as.Date(Master_Date, format = "%Y-%m-%d")) %>% arrange(Master_Date)
colorP <- c("#F6A704", "#0E1033","#4E7B14","#A92007","#D47E0A")
FMVM <- FM %>%
  mutate(Product_Audience = paste0(Code_Product, "_", Code_Audience)) %>%
  group_by(Code_Audience,Code_Product, Code_Vendor, Code_Medium,Week = as.Date(cut(Master_Date + 1, "week")), format = "%Y-%m-%d") %>%
  summarise(
    Cost = sum(Master_Cost),
    Clicks = sum(Master_Clicks),
    Impressions = round(sum(Master_Impressions),0),
    #CTR = paste0(round(Clicks/Impressions * 100, 2), "%"),
    Bounces = sum(Master_Bounces),
    Sessions = sum(Master_Sessions),
    UPV = sum(Master_Unique_Pageviews),
    Views = sum(Master_Views),
    Completions = sum(Master_Completions),
    #BounceRate = paste0(round(Bounces/Sessions * 100, 2), "%"),
    Step1 = sum(Master_Time_On_Page)/(sum(Master_Pageviews)- sum(Master_Exits)),
    Av_TOP = round_hms(as_hms(Step1), 5),
    ClickRatePct = round(Clicks/Impressions * 100, 2),
    BounceRatePct = round(Bounces/Sessions * 100, 2),
    ViewRate = round(Views/Impressions * 100, 2),
    VTR = round(Completions/Impressions *100, 2),
    ClickableCompletions = sum(Master_Clickable_Completions),
    ClickableCompRate = round(Clicks/ClickableCompletions * 100, 2), 
    Swipes = sum(Master_Swipes), 
    SwipeUpRatePct = round(Swipes/Impressions * 100, 2),
    Opens = sum(Master_Clicks_To_Site),
    CTOR = round(Opens/Clicks * 100, 2), 
    Sends = sum(Master_Sends), 
    LIOpens = sum(Master_Opens),
    LIClicks = sum(Master_Clicks_Sponsored_InMail),
    OpenRate = round(LIOpens/Sends * 100, 2), 
    Engagements = sum(Master_Engagements),
    EngagementRate = round(Engagements/Impressions * 100, 2),
    EngRate = round((sum(LIOpens)+sum(Engagements))/sum(Sends)*100, 2),  
    LICTOR = round(sum(LIClicks)/sum(LIOpens) * 100, 2)) %>%
  select(Week, Impressions, Clicks, Bounces, Sessions, Swipes, ClickRatePct, SwipeUpRatePct, UPV, BounceRatePct, Av_TOP, ClickableCompRate, VTR, CTOR,OpenRate, Sends, ViewRate, ClickableCompletions, Completions, Opens, LIOpens, LIClicks, Engagements, LICTOR, EngRate, EngagementRate)
```





```{r}
fahrenheit_to_celsius <- function(temp_F) {
  PGCTR <- IGD %>%  
    ggplot(aes(x = Week, y = ClickRatePct , color = Code_Audience)) +
    geom_line(size = 1.2) +
    scale_color_manual(values = colorP) +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    theme(axis.title.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.line = element_line(colour = "black")) +
    theme(axis.title.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank()) +
    geom_hline(yintercept = c(0.45,0.73), linetype="dashed")
  
  PGImp <- IGD %>% 
    ggplot(aes(x = Week, y = Impressions , color = Code_Audience)) +
    geom_line(size = 1.2) +
    scale_color_manual(values = colorP) +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    theme(axis.title.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.line = element_line(colour = "black")) +
    theme(axis.title.x=element_blank(),
          axis.ticks.x=element_blank()) 
  
  
  PGUPV <- IGD %>% 
    ggplot(aes(x = Week, y = UPV , color = Code_Audience)) +
    geom_line(size = 1.2) +
    scale_color_manual(values = colorP) +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    theme(axis.title.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          panel.background = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())
  
  
  
  PGBR <- IGD %>% 
    ggplot(aes(x = Week, y = BounceRatePct , color = Code_Audience)) +
    geom_line(size = 1.2) +
    scale_color_manual(values = colorP) +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    theme(axis.title.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),axis.ticks.x=element_blank())
  
  
  a <- ggarrange(PGImp, PGCTR, PGUPV, PGBR, ncol=4, nrow=1, common.legend = TRUE, legend="right")
  annotate_figure(a, text_grob(paste0( IGD$Code_Vendor, "_ ", IGD$Code_Medium, "_ ", IGD$Code_Product), color = "darkblue", face = "plain", size = 18, just = "right"))
  
  
  
}



```


```{r}
celsius_to_fahrenheight <- function(temp_C){
  YTD <- FMVM %>%
  mutate(ReportingPeriod = "YTD") %>% 
  group_by(Code_Audience, ReportingPeriod) %>%
        summarise(YTD_Impressions = prettyNum(round(sum(Impressions),0), big.mark = ","),
                  Avg_CTR = round(sum(Clicks)/sum(Impressions) * 100, 2),
                  YTD_UPV = prettyNum(round(sum(UPV),0), big.mark = ","), 
                  Avg_BR = paste0(round(sum(Bounces)/sum(Sessions) * 100, 2), "%"),
                  Avg_CTR = paste0(Avg_CTR, "%") )
                  
}
print(celsius_to_fahrenheight())
```


## FB_DISP_UG

```{r}
IGD <- FMVM %>% 
  filter(Code_Vendor == "FB" & Code_Medium == "DISP" & Code_Product == "UG") 
#%>%
  #mutate(Week = as.Date(Week))



fahrenheit_to_celsius(a)
celsius_to_fahrenheight(YTD)
```

## IG_DISP_UG

```{r}
IGD <- FMVM %>% 
  filter(Code_Vendor == "IG" & Code_Medium == "DISP" & Code_Product == "UG") 
#%>%
  #mutate(Week = as.Date(Week))



fahrenheit_to_celsius(a)
celsius_to_fahrenheight(YTD)
```


## DBM_DISP_UG

```{r}
IGD <- FMVM %>% 
  filter(Code_Vendor == "DBM" & Code_Medium == "DISP" & Code_Product == "UG") 
#%>%
  #mutate(Week = as.Date(Week))



fahrenheit_to_celsius(a)
celsius_to_fahrenheight(YTD)
```
